### ISSUE TITLE
Duo Universal Prompt in iFrame?

### ISSUE THREAD

**Issue by milind** [duosecurity/duo_universal_python#12]
Hi! This is really more of a user-experience issue that I'm having, but I was wondering whether there is any way to embed the new universal prompt into my existing website without having the user redirected to the Duo website and then back to mine? From a user perspective, it is quite jarring to go from my website with one (let's say dark) color palette and then to be tossed into a really bright one on the splash screen. If I could embed an iframe of basically just the prompt into my own website, like the old prompt allowed me to do, I think that it would be a much more seamless experience for my users. Happy to talk about it, thanks!

**Comment by AaronAtDuo** [comment]
@milind We will likely never prioritize support for embedding the Universal Prompt in an iframe.  Avoiding an iframe was a major driver for the Universal Prompt project, for a variety of reasons.

Please review the documentation at https://duo.com/docs/administration-settings#custom-branding regarding the custom branding that can be applied to Duo and the Universal Prompt.  Perhaps some of these options can assist in improving your users' experience.

Thanks for using Duo!

**Comment by milind** [comment]
No worries - and then a follow-up question that I had: if I have the website with the universal Duo prompt running in another website's iframe, will I run into issues? I tried a relatively simple example where I created an html sheet with an iframe and set the src attribute to the localhost port where the demo was running and it runs fine outside of the iframe, but gives me a 500 internal server error when I try the iframe version. I would ideally like to have a solution to run my website in another website's iframe but I assume that the limitations that I'm running into are the same reason why the Duo Universal client is unable to be opened in an iframe in the first place.

**Comment by AaronAtDuo** [comment]
@milind I suspect that it won't be feasible to set up the scenario you're describing.  The Duo Universal prompt is definitely not written to support being in an iframe, either directly or, in your case, indirectly.  I bet there's all kind of CORS and XSS issues if you try it.

Perhaps one of our other approaches to authentication (SSO for example) might work better for your use case?

Out of curiosity, what is the server error you got with your simple test?  It might be handy to know, in case other people try the same thing.

**Comment by AaronAtDuo** [comment]
Closing as answered.

**Comment by AaronAtDuo** [comment]
@milind 

Duo is looking to learn how to significantly improve the developer experience and what tools, resources, and technology (eg: sandboxes, new sdks, etc.) would best-enable customers to work faster and build things more easily with Duo's developer ecosystem. If your org is a Duo customer, and you have done development work (ex; authentication integrations, creation of a homegrown admin tool, log consumption for SIEMS, etc) with Duo's developer tools/resources in the past year, we would love to speak with you about your experience, what tools/resources you used, and your pain points.
This will be a 60-minute session during which you’ll have the opportunity to discuss your honest thoughts and feedback with Duo researchers. No preparation is necessary, and please know that this is not a sales call or product demo.
If you’re interested in participating, please email [lli@duosecurity.com](mailto:lli@duosecurity.com) to start the scheduling process.
Once the 60-minute session is complete, you will receive a token of appreciation in the form of a $75 e-gift card through Tremendous (options for Amazon or select retailers).
Please let me know if you have any questions!
Thanks!
