### ISSUE TITLE
PyPI tarball is broken

### ISSUE THREAD

**Issue by kmosiejczuk** [duosecurity/duo_universal_python#14]
The PyPI tarball doesn't include the requirements.txt file which is explicitly used by setup.py

**Comment by AaronAtDuo** [comment]
@kmosiejczuk Thanks for bringing this to our attention.  That's definitely a problem, I'm surprised it hadn't been caught yet.  I guess you're the first person to try the tarball!

I'll try to get this fixed as soon as I can, I need to track down our Python packaging experts.

**Comment by AaronAtDuo** [comment]
@kmosiejczuk Version 2.0.2, just released to PyPi, resolves the issue.  Thanks again for catching this, and thanks for using Duo!

**Comment by kmosiejczuk** [comment]
tarball is still missing a references tests/requirements.txt. I've done pull request #15  that should fix this and include the tests in the PyPI tarball (useful for distributions like OpenBSD)

**Comment by AaronAtDuo** [comment]
@kmosiejczuk Thanks, I'm glad someone that knows what they're doing is working on this :)

I'll take a look at the PR shortly.

**Comment by kmosiejczuk** [comment]
Honestly, I would have done a PR first, but it had just been long enough since I played with MANIFEST.in that I'd need to look it up. So I went with reporting it to get the report in. :D

**Comment by AaronAtDuo** [comment]
This time for sure!
https://pypi.org/project/duo-universal/#files
