### ISSUE TITLE
Bump python dependencies

### ISSUE THREAD

**Issue by rlaunch** [duosecurity/duo_universal_python#2]
Could the python dependencies for this be bumped to latest/highest compatible if possible?

**Comment by AaronAtDuo** [comment]
@rlaunch We've changed the requirements to define minimums that we know work, so you should be able to use later versions.  Does this meet your use case?

**Comment by rlaunch** [comment]
@AaronAtDuo Yes that would be great, thanks!

**Comment by AaronAtDuo** [comment]
Dependencies have been changed to minimums (in general).  pyJWT 2.0 breaks tests at the moment, we'll look into updating that soon.  We'll release to PyPi shortly.
