### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED error due to missing parameter in duo.conf

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [duosecurity/duo_universal_python#26]
Following [readme](https://github.com/duosecurity/duo_universal_python/tree/main/demo) still leads to
```
duo_universal.client.DuoException: HTTPSConnectionPool(host='api-duo1.duo.test', port=443): Max retries exceeded with url: /oauth/v1/health_check (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:997)')))
```
Solve it by adding
```
duo_certs = DISABLE
```
to your `duo.conf` file
## Steps to Reproduce

1.
2.
3.
4.

**Comment by AaronAtDuo** [comment]
Bypassing the certificate pinning is a 'feature' that should only be used in development.  I don't want to add anything related to it into the standard configuration file, so users of this library don't accidentally use it.
