### ISSUE TITLE
Typo in health_check documentation

### ISSUE THREAD

**Issue by nickineering** [duosecurity/duo_universal_python#7]
https://duo.com/docs/duoweb#call-health_check()

You include the following example code at the above url:

```
try:
  duo_client.healthcheck()
```

That does not work for me, but with an underscore it does. I assume it is a typo and it should actually read the following:

```
try:
  duo_client.health_check()
```

**Comment by DuoKristina** [comment]
Thanks for reporting this. The correction is in the publishing queue.
