### ISSUE TITLE
M1 Mac Install

### ISSUE THREAD

**Issue by milind** [duosecurity/duo_universal_python#9]
I am currently running a late 2020 MacBook Air with an M1 chip and I was unable to install using conda / pip through any of the suggested channels. Curious if anyone else had any luck installing the package on an M1 Mac and what your process was to get it to work. Please let me know if you need any more information and I'm happy to provide it.

**Comment by AaronAtDuo** [comment]
@milind I'll see if I can track down one of my mac-using teammates to give it a try, but in the meantime, can you post any error messages or other output you get when you try to install?

**Comment by milind** [comment]
Thanks for the fast reply! This is the error message that I get when I tried `pip install duo_universal`:

```
ERROR: Command errored out with exit status 1: /Users/user/miniforge3/envs/duo-demo/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c1/06y4bhv92bv93g70gkhdj8nc0000gn/T/pip-install-aypsaeg1/cffi_531d88866a3e438daff1b09641bf3f7b/setup.py'"'"'; __file__='"'"'/private/var/folders/c1/06y4bhv92bv93g70gkhdj8nc0000gn/T/pip-install-aypsaeg1/cffi_531d88866a3e438daff1b09641bf3f7b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c1/06y4bhv92bv93g70gkhdj8nc0000gn/T/pip-record-lfu8_4_m/install-record.txt --single-version-externally-managed --compile --install-headers /Users/user/miniforge3/envs/duo-demo/include/python3.9/cffi Check the logs for full command output.
```

**Comment by AaronAtDuo** [comment]
Wow, that's not like anything I've ever seen before.  I'll see what I can find but hopefully someone who knows Macs will have some ideas.

**Comment by AaronAtDuo** [comment]
@milind We were never able to reproduce this internally, or figure out the cause or solution.  Any luck for you?

**Comment by milind** [comment]
Hi Aaron - thanks for getting back to me! So I put this on the back-burner for a bit while working on some other things but using the same procedure as I had before, it seems to work now? I think the last time I had run this, it had some issue with the cffi library (?) but that does not seem to be an issue anymore. Thanks again for the help and looking forward to playing around with this!
